// This file is generated by Astro DB
declare module 'astro:db' {
	export const Session: import("@astrojs/db/runtime").Table<
		"Session",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Session","primaryKey":false,"optional":false}},"access_token":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"access_token","collection":"Session","primaryKey":false,"optional":false}},"refresh_token":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"refresh_token","collection":"Session","primaryKey":false,"optional":false}},"image":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"image","collection":"Session","primaryKey":false,"optional":false}},"primary_color":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"primary_color","collection":"Session","primaryKey":false,"optional":false}},"secondary_color":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"secondary_color","collection":"Session","primaryKey":false,"optional":false}},"menu":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"menu","collection":"Session","primaryKey":false,"optional":false}}}
	>;
}
